name: Visual Regression Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

# Grant GITHUB_TOKEN the permissions required to comment on PRs
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  visual-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build the project for testing
      run: npm run build:test

    - name: Verify build output
      run: |
        echo "Checking build output..."
        ls -la dist/ || echo "❌ dist/ directory not found"
        if [ ! -d "dist" ]; then
          echo "❌ Build failed - no dist directory found"
          exit 1
        fi
        echo "✅ Build output verified"

    - name: Start preview server
      run: |
        echo "Starting Node.js server..."
        nohup node ./dist/server/entry.mjs > server.log 2>&1 &
        echo "Server started with PID: $!"
        echo "SERVER_PID=$!" >> $GITHUB_ENV
      
    - name: Wait for server to be ready
      run: |
        echo "Waiting for server to be ready..."
        for i in {1..30}; do
          if curl -s -f http://localhost:4321 > /dev/null 2>&1; then
            echo "✅ Server is ready!"
            exit 0
          fi
          echo "⏳ Attempt $i: Server not ready yet, waiting 2 seconds..."
          sleep 2
        done
        echo "❌ Server failed to start after 60 seconds"
        echo "Server logs:"
        cat server.log || echo "No server logs found"
        exit 1

    - name: Run Playwright tests
      id: test-step
      run: npm run test:visual
      continue-on-error: true

    - name: Show server logs on failure
      if: failure()
      run: |
        echo "📋 Server logs (last 50 lines):"
        tail -50 server.log || echo "No server logs found"

    - name: Stop preview server
      if: always()
      run: |
        if [ ! -z "$SERVER_PID" ]; then
          echo "Stopping server with PID: $SERVER_PID"
          kill $SERVER_PID || true
        fi

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test results on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

    - name: Upload updated screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: updated-screenshots
        path: tests/visual/homepage/homepage.spec.js-snapshots/
        retention-days: 30

    - name: Comment PR with test results
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if there are test failures by examining the test step outcome
          const testStepOutcome = '${{ steps.test-step.outcome }}';
          const hasFailures = testStepOutcome === 'failure';
          
          console.log(`Test step outcome: ${testStepOutcome}`);
          console.log(`Has failures: ${hasFailures}`);
          
          const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
          
          if (hasFailures) {
            const comment = `## 📷 Visual Regression Tests - Changes Detected
          
          Visual tests have detected differences in the screenshots.
          
          **Available actions:**
          - 📥 [Download updated screenshots](${runUrl}) (artifacts: \`updated-screenshots\`)
          - 📊 [View full report](${runUrl}) (artifacts: \`playwright-report\`)
          
          **Are these changes intentional?**
          - ✅ If the changes are correct, download the new screenshots and upload them to the repository
          - ❌ If they are unintentional, review the changes in your code
          
          📝 **How to update baselines:**
          \`\`\`bash
          # Run tests locally to generate new screenshots
          npm run test:visual
          
          # Or force update all screenshots
          npm run test:visual -- --update-snapshots
          \`\`\``;
          
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } else {
            const comment = `## ✅ Visual Regression Tests - Successful
          
          All visual tests have passed correctly. No unexpected visual changes were detected.`;
          
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } 